name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  AUTOMATED_TESTING: 1

jobs:
  perl:
    runs-on: windows-latest
    
    #permissions:
    #  id-token: write
    #  contents: read
    #  attestations: write

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
          distribution: strawberry
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure --verbose

      - name: Build
        run: |
          #echo 1
          pp -E"say qq{Packed using PAR::Packer}" -o check.exe
          ls

       #- name: Attest
       #  uses: actions/attest-build-provenance@v2
       #  with:
       #   subject-path: '${{ github.workspace }}/check.exe'
