name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  AUTOMATED_TESTING: 1

jobs:
  perl:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
          distribution: strawberry
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure --verbose

      - name: run tests
        run: |
          #echo 1
          perl -E'say join q{ }, @INC'
          prove -l t
